# hook-PyQt5.py - Generated by fix_icons.py
from PyInstaller.utils.hooks import collect_data_files

# Collect PyQt5 data files
datas = collect_data_files('PyQt5')

# Add Qt plugin paths
qt_plugin_paths = []

# Add imageformats plugins
imageformats_dir = r"C:\Users\97253\Desktop\BeastMode-CSIntro-Excercises\CousinTestProject\venv_38\lib\site-packages\PyQt5\Qt5\plugins\imageformats"
if os.path.exists(imageformats_dir):
    qt_plugin_paths.append((imageformats_dir, os.path.join('PyQt5', 'Qt5', 'plugins', 'imageformats')))

# Add platform plugins  
platforms_dir = r"C:\Users\97253\Desktop\BeastMode-CSIntro-Excercises\CousinTestProject\venv_38\lib\site-packages\PyQt5\Qt5\plugins\platforms"
if os.path.exists(platforms_dir):
    qt_plugin_paths.append((platforms_dir, os.path.join('PyQt5', 'Qt5', 'plugins', 'platforms')))

# Add other plugin directories as needed
styles_dir = r"C:\Users\97253\Desktop\BeastMode-CSIntro-Excercises\CousinTestProject\venv_38\lib\site-packages\PyQt5\Qt5\plugins\styles"
if os.path.exists(styles_dir):
    qt_plugin_paths.append((styles_dir, os.path.join('PyQt5', 'Qt5', 'plugins', 'styles')))

# Add all plugin paths to datas
for plugin_source, plugin_dest in qt_plugin_paths:
    if os.path.exists(plugin_source):
        datas.append((plugin_source, plugin_dest))

# Hidden imports
hiddenimports = ['PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets', 'PyQt5.QtSvg']
